CREATE TABLE IF NOT EXISTS user_full_data
(
id INT AUTO_INCREMENT PRIMARY KEY,
role TINYINT(1) UNSIGNED DEFAULT 0,
profile_picture VARCHAR(255) DEFAULT 'public/images/defaultProfilePictureUser.jpg',
name VARCHAR(50),
last_name VARCHAR(50),
birthday DATE NOT NULL,
phone VARCHAR(20) UNIQUE,
email VARCHAR(80) NOT NULL UNIQUE,
country VARCHAR(14) NOT NULL,
city VARCHAR(50),
is_confirmed TINYINT(1) UNSIGNED DEFAULT 0,
confirmation_code VARCHAR(100),
recovery_code VARCHAR(100),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
is_active TINYINT(1) UNSIGNED DEFAULT 1
)