CREATE TABLE IF NOT EXISTS users
(
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL UNIQUE,
username VARCHAR(25) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
last_online_at DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES user_full_data(id) ON DELETE CASCADE
)