CREATE TABLE IF NOT EXISTS artists
(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
cover_picture VARCHAR(255) DEFAULT 'public/images/defaultCoverPictureArtist.jpg',
country VARCHAR(50) NOT NULL,
bio TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
is_active TINYINT(1) DEFAULT 1
)