spring:
  application:
    name: server
    
  #db configuration data
  datasource:
    url: jdbc:mysql://localhost:3308/Test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
  logging:
    level:
      org.springframework.mail: DEBUG
      hibernate:
        #FOR TESTING ONLY!!!
        format_sql: true
    #FOR TESTING ONLY!!!
    show-sql: true

  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamano
    sort:
      sort-parameter: orden

server:
  error:
    include-stacktrace: never


#  mvc:
#    servlet:
#      path: /api/v1/demo
