spring:
  application:
    name: server
    
  #db configuration data
  datasource:
    url: jdbc:mysql://localhost:3308/Test
    username: root
    password: 5N6a2h3u0e8l6G-1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  logging:
    level:
      org:
        springframework:
          mail: DEBUG
      hibernate:
        #FOR TESTING ONLY!!!
        format_sql: true
    #FOR TESTING ONLY!!!
    show-sql: true

  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamano
    sort:
      sort-parameter: orden

server:
  error:
    include-stacktrace: never


#  mvc:
#    servlet:
#      path: /api/v1/demo
